import {
  ShoppingCart,
  History,
  Ban,
  BarChart3,
  DollarSign,
  Users,
  Shield,
  KeyRound,
  Package,
  Grid2X2,
  Image,
  MapPin,
  Clock3,
  CreditCard,
  Palette,
  Smartphone,
  Megaphone,
  Home,
  Layout,
  MessageCircle,
  Settings,
  ClipboardList,
  Star,
  CalendarDays,
  Rocket,
  BookOpen,
  FileText,
  Search,
  Wrench,
} from "lucide-react";
import type { ReactNode } from "react";

export type RestaurantModule = {
  code: string;
  title: string;
  description: string;
  href: (restaurantId: string) => string;
  color: string;
  category:
    | "experience"
    | "operation"
    | "business"
    | "admin"
    | "system";
  icon: ReactNode;
};

/**
 * Canonical module registry for the restaurant context.
 * Super Admin sees all of them; restaurant users see the modules
 * assigned to their role via role_modules.
 */
export const restaurantModules: RestaurantModule[] = [
  // EXPERIENCIA
  {
    code: "hero",
    title: "Hero",
    description: "Slides, banners y mensajes principales.",
    category: "experience",
    color: "#3b82f6",
    icon: <Home size={18} />,
    href: (id) => `/super-admin/restaurants/${id}/settings/hero`,
  },
  {
    code: "navbar",
    title: "Navbar",
    description: "Logo y navegación principal.",
    category: "experience",
    color: "#3b82f6",
    icon: <Layout size={18} />,
    href: (id) => `/super-admin/restaurants/${id}/settings/navbar`,
  },
  {
    code: "serviciosrestaurant",
    title: "Servicios Restaurant",
    description: "Beneficios e iconos destacados.",
    category: "experience",
    color: "#3b82f6",
    icon: <Star size={18} />,
    href: (id) => `/super-admin/restaurants/${id}/settings/serviciosrestaurant`,
  },
  {
    code: "cta",
    title: "CTA",
    description: "Botones y llamadas a la acción.",
    category: "experience",
    color: "#3b82f6",
    icon: <Rocket size={18} />,
    href: (id) => `/super-admin/restaurants/${id}/settings/cta`,
  },
  {
    code: "about",
    title: "About",
    description: "Historia y presentación.",
    category: "experience",
    color: "#3b82f6",
    icon: <BookOpen size={18} />,
    href: (id) => `/super-admin/restaurants/${id}/settings/about`,
  },
  {
    code: "footer",
    title: "Footer",
    description: "Branding y datos finales.",
    category: "experience",
    color: "#3b82f6",
    icon: <FileText size={18} />,
    href: (id) => `/super-admin/restaurants/${id}/settings/footer`,
  },
  {
    code: "socials",
    title: "Redes Sociales",
    description: "Redes sociales y contacto.",
    category: "experience",
    color: "#ec4899",
    icon: <MessageCircle size={18} />,
    href: (id) => `/super-admin/restaurants/${id}/settings/socials`,
  },
  {
    code: "themes",
    title: "Tema",
    description: "Colores y tipografía.",
    category: "experience",
    color: "#a855f7",
    icon: <Palette size={18} />,
    href: (id) => `/super-admin/restaurants/${id}/settings/themes`,
  },

  // OPERACIÓN / MENÚ
  {
    code: "products",
    title: "Productos",
    description: "Menú, precios y disponibilidad.",
    category: "operation",
    color: "#22c55e",
    icon: <Package size={18} />,
    href: (id) => `/super-admin/restaurants/${id}/settings/products`,
  },
  {
    code: "categories",
    title: "Categorías",
    description: "Secciones del menú.",
    category: "operation",
    color: "#06b6d4",
    icon: <Grid2X2 size={18} />,
    href: (id) => `/super-admin/restaurants/${id}/settings/categories`,
  },
  {
    code: "gallery",
    title: "Galería",
    description: "Imágenes del restaurante.",
    category: "operation",
    color: "#ec4899",
    icon: <Image size={18} />,
    href: (id) => `/super-admin/restaurants/${id}/settings/gallery`,
  },
  {
    code: "services",
    title: "Servicios",
    description: "Delivery, Pickup y entregas.",
    category: "operation",
    color: "#22c55e",
    icon: <Wrench size={18} />,
    href: (id) => `/super-admin/restaurants/${id}/settings/services`,
  },
  {
    code: "location",
    title: "Ubicación",
    description: "Mapa y navegación.",
    category: "operation",
    color: "#22c55e",
    icon: <MapPin size={18} />,
    href: (id) => `/super-admin/restaurants/${id}/settings/location`,
  },
  {
    code: "schedule",
    title: "Horarios",
    description: "Días y horarios de atención.",
    category: "operation",
    color: "#f59e0b",
    icon: <Clock3 size={18} />,
    href: (id) => `/super-admin/restaurants/${id}/settings/schedule`,
  },
  {
    code: "reservations_settings",
    title: "Configuración de Reservas",
    description: "Configura el funcionamiento de las reservas online.",
    category: "operation",
    color: "#f59e0b",
    icon: <CalendarDays size={18} />,
    href: (id) => `/super-admin/restaurants/${id}/settings/reservations`,
  },
  {
    code: "payments",
    title: "Pagos",
    description: "Transferencias y métodos.",
    category: "operation",
    color: "#22c55e",
    icon: <CreditCard size={18} />,
    href: (id) => `/super-admin/restaurants/${id}/settings/payments`,
  },
  {
    code: "discover",
    title: "Discover",
    description: "Controla la visibilidad del restaurante en Discover.",
    category: "operation",
    color: "#22c55e",
    icon: <Search size={18} />,
    href: (id) => `/super-admin/restaurants/${id}/settings/discover`,
  },

  // NEGOCIO
  {
    code: "financial",
    title: "Configuración Financiera",
    description: "Comisiones y reglas.",
    category: "business",
    color: "#f97316",
    icon: <Settings size={18} />,
    href: (id) => `/super-admin/restaurants/${id}/settings/financial`,
  },
  {
    code: "finance",
    title: "Finanzas",
    description: "Dashboard financiero.",
    category: "business",
    color: "#22c55e",
    icon: <DollarSign size={18} />,
    href: (id) => `/super-admin/restaurants/${id}/finance`,
  },
  {
    code: "marketing",
    title: "Marketing",
    description: "QR, campañas y material promocional.",
    category: "business",
    color: "#f43f5e",
    icon: <Megaphone size={18} />,
    href: (id) => `/super-admin/restaurants/${id}/settings/marketing`,
  },
  {
    code: "google_reviews",
    title: "Google Reviews",
    description: "Gestiona reseñas, QR y material promocional.",
    category: "business",
    color: "#4285f4",
    icon: <Star size={18} />,
    href: (id) => `/super-admin/restaurants/${id}/settings/google-reviews`,
  },
  {
    code: "analytics",
    title: "Analytics",
    description: "Métricas generales de pedidos.",
    category: "business",
    color: "#8b5cf6",
    icon: <BarChart3 size={18} />,
    href: (id) => `/admin/orders/${id}/orders/analytics`,
  },
  {
    code: "orders",
    title: "Pedidos",
    description: "Panel central de pedidos.",
    category: "business",
    color: "#f97316",
    icon: <ShoppingCart size={18} />,
    href: (id) => `/admin/orders/${id}/orders`,
  },
  {
    code: "reservations",
    title: "Reservas",
    description: "Gestiona las reservas y mesas.",
    category: "business",
    color: "#f97316",
    icon: <CalendarDays size={18} />,
    href: (id) => `/admin/reservations/${id}`,
  },
  {
    code: "history",
    title: "Historial Pedidos",
    description: "Pedidos completados.",
    category: "business",
    color: "#3b82f6",
    icon: <History size={18} />,
    href: (id) => `/admin/orders/${id}/orders/history`,
  },
  {
    code: "cancelled",
    title: "Pedidos Cancelados",
    description: "Registro de cancelaciones.",
    category: "business",
    color: "#ef4444",
    icon: <Ban size={18} />,
    href: (id) => `/admin/orders/${id}/orders/cancelled`,
  },

  // ADMINISTRACIÓN
  {
    code: "users",
    title: "Usuarios",
    description: "Gestión de personal.",
    category: "admin",
    color: "#8b5cf6",
    icon: <Users size={18} />,
    href: (id) => `/super-admin/restaurants/${id}/access/users`,
  },
  {
    code: "roles",
    title: "Roles",
    description: "Cargos del restaurante.",
    category: "admin",
    color: "#8b5cf6",
    icon: <Shield size={18} />,
    href: (id) => `/super-admin/restaurants/${id}/access/roles`,
  },
  {
    code: "permissions",
    title: "Permisos",
    description: "Acceso a módulos.",
    category: "admin",
    color: "#ef4444",
    icon: <KeyRound size={18} />,
    href: (id) => `/super-admin/restaurants/${id}/access/permissions`,
  },
  {
    code: "legal",
    title: "Centro Legal",
    description: "Acuerdos, términos y documentos legales.",
    category: "admin",
    color: "#6366f1",
    icon: <Shield size={18} />,
    href: () => `/super-admin/legal`,
  },
  {
    code: "requests",
    title: "Solicitudes",
    description: "Gestiona las solicitudes del restaurante.",
    category: "admin",
    color: "#f97316",
    icon: <ClipboardList size={18} />,
    href: (id) => `/super-admin/restaurants/${id}/settings/requests`,
  },

  // SISTEMA
  {
    code: "restaurant_edit",
    title: "Editar Restaurante",
    description: "Configuración principal.",
    category: "system",
    color: "#ec4899",
    icon: <Settings size={18} />,
    href: (id) => `/super-admin/restaurants/${id}/edit`,
  },
  {
    code: "restaurants",
    title: "Listado Restaurantes",
    description: "Volver al listado.",
    category: "system",
    color: "#ec4899",
    icon: <Grid2X2 size={18} />,
    href: () => `/super-admin/restaurants`,
  },
  {
    code: "restaurant_new",
    title: "Nuevo Restaurante",
    description: "Crear restaurante.",
    category: "system",
    color: "#ec4899",
    icon: <ShoppingCart size={18} />,
    href: () => `/super-admin/restaurants/new`,
  },
  {
    code: "pwa",
    title: "PWA",
    description: "Aplicación e instalación.",
    category: "system",
    color: "#14b8a6",
    icon: <Smartphone size={18} />,
    href: (id) => `/super-admin/restaurants/${id}/settings/pwa`,
  },
];

export const RESTAURANT_MODULE_COUNT = restaurantModules.length;
